import firebase from 'firebase/app';
import 'firebase/auth';

const buildCrew = (crew) => {
  const userDelete = firebase.auth().currentUser === null ? '' : '<i class="delete-crew delete-btn far fa-2x fa-times-circle"></i>';
  const userEdit = firebase.auth().currentUser === null ? '' : '<i class="crew-edit-button edit-btn fas fa-edit fa-2x"></i>';
  let domString = '';
  domString += `<div id="${crew.id}" class="fancy-card crew show-delete-button">`;
  domString += '<div class="additional">';
  domString += '<div class="user-card">';
  domString += `<img class="center" height="250px" src=" ${crew.img}" alt="image of ${crew.img}">`;
  domString += `${userDelete}`;
  domString += `${userEdit}`;
  domString += '</div>';
  domString += '<div class="more-info shading" >';
  domString += `<div class="card-title mb-1 mt-3 ml-3 mr-3">  ${crew.name} </div>`;
  domString += '<div class=" mt-4 ml-5">';
  domString += '<div class="mt-2 text-white">';
  domString += '<i class="fas fa-home"></i>';
  domString += `<span>  ${crew.baseCity} </span>`;
  domString += '</div>';
  domString += '<div class="mt-2 text-white">';
  domString += '<i class="fas fa-cogs"></i>';
  domString += `<span>  ${crew.position} </span>`;
  domString += '</div>';
  domString += '<div class="mt-2 text-white">';
  domString += '<i class="fas fa-user-plus"></i>';
  domString += `<span>  ${crew.hireDate} </span>`;
  domString += '</div>';
  domString += '</div>';
  domString += '</div>';
  domString += '</div>';
  domString += '<div class="general hubGeneral">';
  domString += `<div class="card-title mb-1 mt-3"> ${crew.name}</div>`;
  domString += '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce a volutpat mauris, at molestie lacus. Nam vestibulum sodales odio ut pulvinar.</p>';
  domString += '<span class="more">Mouse over the card for more info</span>';
  domString += '</div>';
  domString += '</div>';
  return domString;
};
export default { buildCrew };
